baseURL = "https://chloematt.com/"
languageCode = "en-gb"
title = "Digital Product Strategy and Development Firm"
theme = "chloematt"

[params]

  [params.navbarlogo]
  image = "logos/cm_logotype_light.png"
  link = "/"

  [params.font]
  name = "Open Sans"
  sizes = [
    400.0,
    600.0
  ]

  [params.hero]
  title = "Innovation & Values"
  subtitle = "Chloe & Matt is a digital product strategy and development firm helping companies to innovate through collaboration. We help your company to build digital products and services by combining customer research and insights to bring great impacts."
  buttontext = "Download Company Profile"
  buttonlink = "#"
  image = "illustrations/CM-coinnovation.svg"
  clientlogos = []

  [params.section1]
  title = "What We Do"
  subtitle = "Our services to help you achieve the goal."

    [[params.section1.tiles]]
    title = "Web Development"
    icon = "mouse-globe"
    text = "From static to dynamic web development in PHP and JS."
    url = "/"
    buttonText = "Contact Us"

    [[params.section1.tiles]]
    title = "Mobile App Development"
    icon = "laptop-cloud"
    text = "Cross-platform development with React Native."
    url = "/"
    buttonText = "Contact Us"

    [[params.section1.tiles]]
    title = "Managed Service"
    icon = "plug-cloud"
    text = "Maintain your digital infrastructures."
    url = "/"
    buttonText = "Contact Us"

  [params.section2]
  title = "The Playbook"
  subtitle = "The typical timeframe while working with us."

    [[params.section2.features]]
    title = "Customer Interview"
    text = "The first step before we start doing the development. The output of this process is getting customers insight and value propositions."
    icon = "playbook-CI"

    [[params.section2.features]]
    title = "Sprint-Up"
    text = "Start building the interactive prototype, product identities, and product features."
    icon = "playbook-DS"

    [[params.section2.features]]
    title = "Agile Development"
    text = "The process of designing and developing your digital product."
    icon = "playbook-AD"

    [[params.section2.features]]
    title = "Product Testing"
    text = "The testing phase before releasing the product to the market."
    icon = "playbook-PT"

  [params.section5]
  title = "Contact"

  [params.footer]
  logo = "cm_color.png"
  bulmalogo = false

    [[params.footer.socialmedia]]
    link = "https://www.instagram.com/chloenmatt/"
    icon = "instagram"

    [[params.footer.socialmedia]]
    link = "https://github.com/chloe-matt"
    icon = "github"

  [[params.navbar]]
  title = "Services"
  url = "/"

  [[params.navbar]]
  title = "About Us"
  url = "/"

  [[params.navbar]]
  title = "Contact"
  url = "/"
  button = false