name = "AppLover"
license = "MIT"
licenselink = ""
description = "2019 C&M's website theme"
homepage = "https://chloematt.com"
tags = ["responsive", "light", "company", "clean", "chloe & matt"]
features = []
min_version = "0.54"

[author]
  name = "Retno Ika S."
  homepage = "https://github.com/retnoika"